---
- hosts: all 
  gather_facts: no
  serial: 5
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay-DCs.yml"
      name: underlay
  - name: Create lab-reset config
    template:
      src: "{{lookup('env','PWD')}}/templates/lab-reset.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_lab-reset.cfg"
  - name: Upload config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_lab-reset.cfg"
