---
- hosts: leaf1-DC1
  gather_facts: no
  serial: 5
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/overlay-DCs.yml"
      name: overlay
  - name: Create Leaf config
    template:
      src: "{{lookup('env','PWD')}}/templates/leaf-overlay.j2"
      dest: "{{lookup('env','PWD')}}/configs/overlay_{{inventory_hostname}}.cfg"
  - name: Upload config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/overlay_{{inventory_hostname}}.cfg"
